### ISSUE TITLE
pam_unix: curdays == spent->sp_lstchg && spent->sp_max == spent->sp_warn, no warning

### ISSUE THREAD

**Issue by DZH-CS** [linux-pam/linux-pam#167]
if (curdays == spent->sp_lstchg && spent->sp_max == spent->sp_warn)
            no warn

**Comment by DZH-CS** [comment]
mod: if ((curdays - spent->sp_lstchg >= spent->sp_max - spent->sp_warn)

**Comment by t8m** [comment]
Unfortunately I do not understand what do you want to report and suggest here. Could you please describe the problem in detail?

**Comment by DZH-CS** [comment]
Sorry, my english is pool.

First of all, if the password is changed today, and the maximum number of password warning days is the same, the password expiration days will not be reminded today. Probably in most cases, it will not have an impact.

I don't know if my idea is right, but today I have this problem.

**Comment by DZH-CS** [comment]
> Unfortunately I do not understand what do you want to report and suggest here. Could you please describe the problem in detail?

this way if the sp_warn is set to for example 1 - to warn 1 day before the actual password expiration - the warning would be given for 2 days before the actual expiration happens. 
--------so, Not counted today?

**Comment by t8m** [comment]
It is really depending on what is meant by warn 1 day before the expiration - if it means to warn for 1 whole day or warn since beginning of the calendar day that is 1 day before the expiration happens. That effectively means the warning would be given for 2 days even if the sp_warn is set to 1. And it would not even be possible to display the warning only for 1 calendar day as sp_warn set to 0 would not have any effect.
