### ISSUE TITLE
[RFE]  PAM-level integration of prctl(PR_SET_NO_NEW_PRIVS, ...)

### ISSUE THREAD

**Issue by vcaputo** [linux-pam/linux-pam#224]
I want to enforce this prctl() at login time in the same spirit of things found in /etc/security/limits.conf.

Would a PR adding a no_new_privs option to modules/pam_limits.c be considered for acceptance upstream?

LMK if this is already supported and I'm just missing something.  What I'm interested in is a user/group-oriented way of forcing PR_SET_NO_NEW_PRIVS @ login time.

**Comment by t8m** [comment]
Do you mean a new item for limits.conf? In that case it should be probably named nonewprivs without underscores to align with the other items. I suppose it should be somewhat acceptable for pam_limits instead of creating a completely new module just for this purpose and duplicating all the user/group matching there.
@ldv-alt @thkukuk  What is your opinion?

**Comment by vcaputo** [comment]
> Do you mean a new item for limits.conf?

Yep!  No opinion here on naming, with or without underscores, doesn't matter to me.  Seems like a trivial patch.

**Comment by ldv-alt** [comment]
On Tue, May 12, 2020 at 04:37:20AM -0700, Tomáš Mráz wrote:
> Do you mean a new item for limits.conf? In that case it should be probably named nonewprivs without underscores to align with the other items. I suppose it should be somewhat acceptable for pam_limits instead of creating a completely new module just for this purpose and duplicating all the user/group matching there.
> @ldv-alt @thkukuk  What is your opinion?

I concur.
