### ISSUE TITLE
Incompatibility with systemd 249

### ISSUE THREAD

**Issue by Arfrever** [linux-pam/linux-pam#379]
When systemd >=249 is installed and `nsswitch.conf` contains:
```
shadow:     files systemd
```
And when PAM code is run by process with non-root user, authentication will fail.
See https://bugs.gentoo.org/803050 for more details.

**Comment by floppym** [comment]
To summarize:

Commit f220cace205332a3dc34e7b37a85e7627e097e7d changed pam_unix so that it only executes unix_chkpwd if getspnam sets errno to EACCES.

This relies on libnss_files setting errno to EACCES when /etc/shadow cannot be opened.

If libnss_files is not the last NSS module listed for the shadow database, subsequent NSS modules (like libnss_systemd) may overwrite errno with some other value (like 0).

**Comment by ldv-alt** [comment]
On Fri, Jul 23, 2021 at 01:17:00PM -0700, Mike Gilbert wrote:
> Commit f220cace205332a3dc34e7b37a85e7627e097e7d changed pam_unix so that it only executes unix_chkpwd if getspnam sets errno to EACCES.
> 
> This relies on libnss_files setting errno to EACCES when /etc/shadow cannot be opened.
> 
> If libnss_files is not the last NSS module listed for the shadow database, subsequent NSS modules (like libnss_systemd) may overwrite errno with some other value (like 0).

nss modules are not permitted to do that because such behaviour
would violate the getspnam(3) contract.  Please file a bug report
to the incompatible nss module.

**Comment by floppym** [comment]
What exactly do you mean by "violate contract"?

The man page mentions EACCES if /etc/shadow cannot be opened, but that does not really consider the possibility of NSS modules that do not even attempt to open this file .

**Comment by ldv-alt** [comment]
On Sun, Jul 25, 2021 at 08:19:04AM -0700, Mike Gilbert wrote:
> What exactly do you mean by "violate contract"?
> 
> The man page mentions EACCES if /etc/shadow cannot be opened, but that does not really consider the possibility of NSS modules that do not even attempt to open this file .

The manual page says that EACCES shall be set when the caller does not
have permission to access the shadow password file.

In this case getspnam/getspnam_r tried to access the shadow password file
but, apparently, the error code was lost.

**Comment by ldv-alt** [comment]
From pam_unix perspective, looks like it can fall back to the helper in case of any error returned by `pam_modutil_getspnam`, not just `EACCES`; it falls back to the helper in case of `SELINUX_ENABLED` anyway.  This way the problem caused by libnss_systemd can be avoided in pam_unix, but no doubts it will arise in other users of `getspnam`/`getspnam_r`.
@t8m, what do you think about this workaround?

**Comment by t8m** [comment]
I do not see a big deal with removing the condition and always calling the helper if getspnam returns NULL.
