### ISSUE TITLE
PAM rules for (authenticator & password) | (authenticator & publickey)

### ISSUE THREAD

**Issue by SSchott** [linux-pam/linux-pam#453]
For long I have been wondering how one could setup the, let's say, a conventional "password | publickey" with added google_authenticator. If I understand things correctly, only OpenSSH deals with publickeys at the moment? Is there any way to "properly" implement this? At the moment I have it working with the annoyance of having to pass the password every time, so more like "authenticator & password".

Here my sshd file in an OpenSuse install:
```
auth        requisite   pam_nologin.so
auth        required    pam_env.so
auth        required    pam_unix.so     nis try_first_pass
auth   [success=1  default=ignore] pam_access.so accessfile=/etc/security/access-local.conf
auth        required    pam_google_authenticator.so grace_period=43200
account     requisite   pam_nologin.so
account     include     common-account
password    include     common-password
session     required    pam_loginuid.so
session     include     common-session
session     optional    pam_lastlog.so   silent noupdate showfailed
session     optional    pam_keyinit.so   force revoke
```

while in the sshd_config I have

```
...
UsePAM yes
PasswordAuthentication yes
AuthenticationMethods keyboard-interactive
...
```

I have tried with `AuthenticationMethods keyboard-interactive,publickey keyboard-interactive,password`, but I ended up with PAM and SSH requesting the password more than once, so it got really confusing at some point. If anyone has any clue on how this could be done, or who else I could annoy with this idea, I am all ears.

**Comment by t8m** [comment]
This is a question that should be directed at OpenSSH maintainers rather than us. However unless OpenSSH allows having separate pam stacks for different optional AuthenticatioMethods I do not think this is solvable.

If you were OK to just have a public key authentication with google authenticator and no password authentication at all, then I would configure the pam auth stack with just the pam_google_authenticator and no pam_unix.

The other option (maybe more reasonable) is to accept that the public key authentication is OK by itself and and require both password and google authenticator. In that case you will set `PasswordAuthentication no` enable public key authentication and keep your pam stack configuration.

**Comment by t8m** [comment]
It would be probably a nice RFE for sshd to use different pam stack if you have multiple keyboard-interactive authentication methods configuration. Or make it possible to configure a different pam auth stack for keyboard-interactive and password authentication.

**Comment by t8m** [comment]
Did this answer your question?

**Comment by SSchott** [comment]
Thanks for the reply. Yeah, I was afraid that was going to be the answer 🤣. I know that `authenticator & password | publickey` is a common setup, but still wanted a user to actively request access (at least every 12 hours, given the grace_period).

I will close it then.
