### ISSUE TITLE
Is it okay to link against libpam when depending on a module that contains GPL code?

### ISSUE THREAD

**Issue by kbielefe** [linux-pam/linux-pam#480]
A few files in modules, such as [yppasswd.h](https://github.com/linux-pam/linux-pam/blob/master/modules/pam_unix/yppasswd.h), state they are GPL licensed. We want to create code that links with libpam and requires that particular module to function. Does this make it a [single combined program](http://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins) and therefore subject to the terms of the GPL? That seems an uncommon interpretation, but we want to be respectful of the author's intent here.

**Comment by ldv-alt** [comment]
Given that [yppasswd.h](https://github.com/linux-pam/linux-pam/blob/master/modules/pam_unix/yppasswd.h) contains no code, I'd say that particular file is not an issue.  However, [yppasswd_xdr.c](https://github.com/linux-pam/linux-pam/blob/master/modules/pam_unix/yppasswd_xdr.c) contains some code, so the question stands.

**Comment by thkukuk** [comment]
Question is, if somebody can really claim a copyright on this files?
They are generated with rpcgen from rpcsvc/yppasswd.x, and this file has in the latest version:
/* @(#)yppasswd.x       2.1 88/08/01 4.0 RPCSRC */

/*
 * Copyright (c) 2010, Oracle America, Inc.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *     * Neither the name of the "Oracle America, Inc." nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *   COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 *   INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 *   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 *   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

But in general: NIS shouldn't be used anymore today at all, there is absolute no excuse to still use that.

**Comment by kbielefe** [comment]
> But in general: NIS shouldn't be used anymore today at all, there is absolute no excuse to still use that.

Whether it's used or not, it's compiled together with the rest of the pam_unix module unless configured with `--disable-nis`. Would it typically be disabled in most Linux distros?

**Comment by thkukuk** [comment]
> Whether it's used or not, it's compiled together with the rest of the pam_unix module unless configured with `--disable-nis`. Would it typically be disabled in most Linux distros?

It's always compiled into the pam_unix module, even if not used :( Another bug...
I don't know about other Linux distros, but on openSUSE we disabled the NIS code in Linux-PAM long ago and started to remove NIS completely.

**Comment by ldv-alt** [comment]
Closed #480 as completed via #522.
