### ISSUE TITLE
misc_conv does not respect PAM_MAX_RESP_SIZE

### ISSUE THREAD

**Issue by casantos** [linux-pam/linux-pam#59]
I had to increase PAM_MAX_RESP_SIZE to 1040 bytes (in libpam/include/security/_pam_types.h) to support long passwords (RSA hashes). It did work, however, because the read_string function (in libpam_misc/misc_conv.c) uses INPUTSIZE, which is defined as PAM_MAX_MSG_SIZE.

In order to solve the problem I had to apply the following patch:

```
diff --git a/libpam_misc/misc_conv.c b/libpam_misc/misc_conv.c
index be53f34..e29ce59 100644
--- a/libpam_misc/misc_conv.c
+++ b/libpam_misc/misc_conv.c
@@ -18,7 +18,7 @@
 #include <security/pam_appl.h>
 #include <security/pam_misc.h>
 
-#define INPUTSIZE PAM_MAX_MSG_SIZE           /* maximum length of input+1 */
+#define INPUTSIZE PAM_MAX_RESP_SIZE          /* maximum length of input+1 */
 #define CONV_ECHO_ON  1                            /* types of echo state */
 #define CONV_ECHO_OFF 0
```

**Comment by xenago** [comment]
Thank you for this helpful note. It appears as though since your post, `INPUTSIZE` was changed to use `PAM_MAX_RESP_SIZE`:
https://github.com/linux-pam/linux-pam/commit/cf0a9e631b838f1e0aca1a5626fdea4d2802cb18

`PAM_MAX_RESP_SIZE` is still set to 512 by default, but it doesn't appear as though the additional patch is required anymore since that change.

In the most recent stable release, it was changed again, and now it uses PAM_MISC_CONV_BUFSIZE, which is tunable via the configuration param `--with-misc-conv-bufsize=<number>`:
https://github.com/linux-pam/linux-pam/commit/55f206447a1e4ee26e307e7a9c069236e823b1a5

**Comment by casantos** [comment]
Thanks for the information. I left the project (and the company) in which the change was required, so I didn't pay attention to the subsequent development of linux-pam. Closing this issue.
