### ISSUE TITLE
Add /etc/security/pam_env.conf.d/

### ISSUE THREAD

**Issue by x746e** [linux-pam/linux-pam#613]
Can we extend pam_env to read the environment not just from `/etc/security/pam_env.conf`, but also from a `/etc/security/pam_env.conf.d/` directory with drop-in files?

I'm working on a Gentoo/ChromiumOS-derived system, where I can't easily modify any files installed by upstream packages, but I can add files into these `*.d` directories.

If the feature request sounds reasonable and like something you'd be willing to accept I'd be happy to implement this.

**Comment by ldv-alt** [comment]
It was implemented by commit 6135c45347b6173e305fda66eef138bde693b795.

**Comment by thkukuk** [comment]
> Can we extend pam_env to read the environment not just from `/etc/security/pam_env.conf`, but also from a `/etc/security/pam_env.conf.d/` directory with drop-in files?

What you want is called "Hermetic `/usr`" and people working already on it, including a formal specification, so that all applications behave in the same way:
* https://0pointer.net/blog/fitting-everything-together.html
* https://github.com/uapi-group/specifications/blob/main/specs/configuration_files_specification.md

So before you duplicate work, look if there isn't already support for libeconf in that code. If yes, you just need to enable that. Linux-PAM, util-linux, shadow and more do support that already.
A list of important, missing applications can be found here:
https://github.com/uapi-group/specifications/issues/76
