### ISSUE TITLE
pam_limits: literal values aren't recognized in limits.conf

### ISSUE THREAD

**Issue by dimich-dmb** [linux-pam/linux-pam#761]
Values "-", "unlimited", "infinity" aren't recognized as `-1`.
`/etc/security/limits.conf`:
```
*                hard    core            unlimited
*                soft    core            0
```
journal:
```
pam_limits(sudo:session): wrong limit value '           unlimited' for limit type 'hard'
```
linux-pam 1.6.0

This pull request seems to fix the issue: https://github.com/linux-pam/linux-pam/pull/760

**Comment by stoeckmann** [comment]
Confirmed. This is a regression introduced with 1.6.0.

I have created PR https://github.com/linux-pam/linux-pam/pull/762 which verifies correctness of values by still considering everything after the third field to be a value, i.e. considering `unlimited for everyone` as a single value instead of truncating it to `unlimited`.

**Comment by dimich-dmb** [comment]
> considering `unlimited for everyone` as a single value instead of truncating it to `unlimited`.

Note another (tiny) issue: e.g. value `37somegarbage` will be converted to `37` by `strtoull()` with no error/warning.
I had to not squash two commits into single PR, my bad. Probably need to create another issue.

**Comment by stoeckmann** [comment]
I've created a lot of PRs without issues in the past, so just a PR with the commit you've already prepared would work totally fine. But it's up to you. If you want to add an issue as well, it won't hurt either.
