### ISSUE TITLE
Inquiry about libcrypto (OpenSSL) Support in pam_unix Module

### ISSUE THREAD

**Issue by samirMhn** [linux-pam/linux-pam#838]
Hello,
I am currently working on a project that requires enhanced security measures, and I am particularly interested in knowing whether there are any plans to support OpenSSL’s libcrypto as a replacement for libcrypt in the pam_unix module.

Given the increasing importance of cryptographic robustness and the capabilities provided by OpenSSL, this change would be highly beneficial for systems where OpenSSL is already a key part of the security infrastructure.

Could you kindly provide any information on whether this support is planned for future releases or if it might already be possible to implement this configuration?

Thank you for your time and assistance.

**Comment by thkukuk** [comment]
Replacing libcrypt with libcrypto doesn't make any sense and will most likely never happen.

The crypt() function from libcrypt provides passphrase hashing to all applications doing password verification, not encryption or something similar as libcrypto does. The later is something which you don't want for passwords, because this would be by design always insecure. Beside that it would not be enough to change pam_unix, you need to change **all** applications doing password based authentication.
If you think the password hash algorithm of libcrypt are not secure enough, please work with the upstream libcrypt project to improve them.

**Comment by samirMhn** [comment]
Hello,

Thank you for your response.

I am not questioning the security of the libcrypt project at all.

The reason I asked this question is that we have OpenSSL as the main cryptography library in our system, and it is FIPS certified. Since libcrypt is not FIPS certified, I wanted to know if replacing it with OpenSSL's libcrypto would be possible.
